services:
  app:
    image: itsmeru/taipeidaytrip:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=mydb
      - MYSQL_PASSWORD=betty520
      - JWT_SECRET=ruruisback
      - ALGORITHM=HS256
    volumes:
      # - /Users/ruru/Desktop/taipei-day-trip:/user/src/app
      - /home/ubuntu/Stage-2-Task/app.py:/app/app.py
    networks:
      - stage-2-task_default

  mydb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "betty520"
    ports:
      - "3306:3306"
    volumes:
      - /Users/ruru/Desktop/taipei-day-trip-db:/var/lib/mysql
      - /home/ubuntu/Stage-2-Task/spot.sql:/docker-entrypoint-initdb.d/spot.sql
    networks:
      - stage-2-task_default
networks:
  stage-2-task_default:
    external: true
