services:
  app:
    build: .
    image: itsmeru/taipeidaytrip:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/Stage-2-Tasks:/app

  redis:
    image: redis:latest
    container_name: myredis
    ports:
      - "6379:6379"
