services:
  app:
    build: .
    image: itsmeru/taipeidaytrip:latest
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=mydb
      - MYSQL_PASSWORD=betty520
      - JWT_SECRET=ruruisback
      - ALGORITHM=HS256
    depends_on:
      db:
        condition: service_healthy
    volumes:
      # - /Users/ruru/Desktop/taipei-day-trip:/user/src/app
      - /home/ubuntu/Stage-2-Task/app.py:/app/app.py

  db:
    image: mysql:latest
    container_name: mydb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "betty520"
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=betty520
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    volumes:
      - /Users/ruru/Desktop/taipei-day-trip-db:/var/lib/mysql
      # - /home/ubuntu/Stage-2-Task/spot.sql:/docker-entrypoint-initdb.d/spot.sql
      # - /Users/ruru/Desktop/taipei-day-trip/spot.sql:/docker-entrypoint-initdb.d/spot.sql
      # - ./my.cnf:/etc/mysql/conf.d/my.cnf