services:
  app:
    build: .
    image: itsmeru/taipeidaytrip:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=mydb
      - MYSQL_PASSWORD=betty520
      - JWT_SECRET=ruruisback
      - ALGORITHM=HS256
    volumes:
      # - /Users/ruru/Desktop/taipei-day-trip:/user/src/app
      - /home/ubuntu/Stage-2-Task/app.py:/app/app.py

  db:
    image: mysql:latest
    container_name: mydb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "betty520"
    ports:
      - "3308:3306"
    volumes:
      - /Users/ruru/Desktop/taipei-day-trip-db:/var/lib/mysql
      - /home/ubuntu/Stage-2-Task/spot.sql:/docker-entrypoint-initdb.d/spot.sql
      # - /Users/ruru/Desktop/taipei-day-trip/spot.sql:/docker-entrypoint-initdb.d/spot.sql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

